# Generated by Django 2.2 on 2019-04-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('produto', models.CharField(max_length=200)),
                ('valor_venda', models.CharField(max_length=200)),
                ('data_cadastro', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'combustivel',
                'managed': False,
            },
        ),
    ]
