# Generated by Django 2.1.4 on 2019-01-31 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
