# Generated by Django 2.1.7 on 2019-04-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('1', 'consulta'), ('2', 'retorno')], max_length=20)),
                ('local', models.CharField(max_length=200)),
                ('avaliacao', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_alimentar', models.CharField(max_length=200)),
                ('periodo', models.CharField(choices=[('1', 'manhã'), ('2', 'tarde'), ('3', 'noite')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('crn', models.CharField(max_length=30)),
                ('especialidades', models.ManyToManyField(related_name='nutricionistas', to='paciente.Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateTimeField(null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(blank='True', choices=[('1', 'masculino'), ('2', 'feminino')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='dieta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Dieta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nutricionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Nutricionista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
    ]
