# Generated by Django 2.1.7 on 2019-03-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_dieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
