# Generated by Django 2.1.7 on 2019-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20190326_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(related_name='dieta', to='paciente.Paciente'),
        ),
    ]
